"""fixed_product_migration

Revision ID: f2852655f05b
Revises: 
Create Date: 2025-09-26 14:19:45.390961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2852655f05b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add columns as nullable first
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('in_stock', sa.Integer(), nullable=True))
        batch_op.drop_column('max_sales')
    
    # Set default values for existing rows
    op.execute("UPDATE products SET category = 'Product' WHERE category IS NULL")
    op.execute("UPDATE products SET in_stock = -1 WHERE in_stock IS NULL")
    
    # Now make the columns non-nullable
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category', nullable=False)
        batch_op.alter_column('in_stock', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_sales', sa.INTEGER(), nullable=False))
        batch_op.drop_column('in_stock')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
